const CREATE = "CREATE";
const UPDATE = "UPDATE";
const DELETE = "DELETE";
const FETCH_ALL = "FETCH_ALL";
const AUTHENTICATION = "AUTHENTICATION";
const LOGOUT = "LOGOUT";
export {
  FETCH_ALL,
  CREATE,
  UPDATE,
  DELETE,
  AUTHENTICATION,
  LOGOUT,
};
